# Site settings
title: Nowling Lab
email: nowling@msoe.edu
description: > # this means to ignore newlines until "baseurl:"
  Web site for the Nowling Lab at the Milwaukee School of Engineering.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://nowling-lab.github.io" # the base hostname & protocol for your site
twitter_username: discretestates
github_username: nowling-lab

# Build settings
markdown: kramdown
